#file: noinspection KubernetesUnknownValues
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
data:
  HT_DEBUG: '{{ .Values.django.debug }}'
  HT_HOST: '*'
  HT_SECRET_KEY: "{{ .Values.django.secretKey }}"
  HT_LOG_LEVEL: {{ .Values.django.logLevel }}
  HT_TIMEZONE: {{ .Values.django.timezone }}
  HT_CORS_DOMAIN: {{ .Values.django.corsDomains }}
  HT_RCRAINFO_ENV: {{ .Values.django.rcrainfoEnv }}
  HT_DB_ENGINE: {{ .Values.db.engine }}
  HT_DB_NAME: {{ .Values.db.name }}
  HT_DB_USER: {{ .Values.db.user }}
  HT_DB_PASSWORD: {{ .Values.db.password }}
  HT_DB_PORT: '{{ .Values.db.port }}'
  HT_DB_HOST: '{{ .Values.db.host }}'
